name: Publish

on:
  push:
    branches:
      - master

jobs:
  charm:
    name: Charm
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        set -eux
        sudo snap install charm --classic
        sudo pip3 install charmcraft

    - name: Publish charm
      env:
        CHARMSTORE_CREDENTIAL: ${{ secrets.CHARMSTORE_CREDENTIAL }}
      run: |
        set -eux
        echo $CHARMSTORE_CREDENTIAL > ~/.go-cookies

        CS_URL="cs:~dex-charmers/oidc-gatekeeper"

        IMAGE=$(yq eval '.resources.oci-image.upstream-source' metadata.yaml)
        tox -e build
        docker pull $IMAGE
        charm push ./*.charm $CS_URL --resource oci-image=$IMAGE

        REVISION=$(charm show $CS_URL --channel unpublished --format yaml | yq e .id-revision.Revision -)
        OCI_VERSION=$(charm list-resources $CS_URL --format yaml --channel unpublished | yq e .0.revision -)
        charm release \
            --channel edge \
            --resource oci-image-$OCI_VERSION \
            $CS_URL-$REVISION
